### ISSUE TITLE
AUCapture hangs or crashes due to invalid color code "-1" when another player joins the lobby

### ISSUE THREAD

**Issue by kurokobo** [automuteus/amonguscapture#267]
## Describe the bug

I have received reports from users that AUCapture hangs or crashes **in rare cases** when another player joins the lobby. The user stated **no mods was used**.

The log shows that the player's color was detected as `-1`. After this, it seems that `PlayerColorToBrush.Convert` raises an exception and crashes.

## Logs

* AUCapture `4.1.0` + Among Us `v2021.5.25.2s`:
  ```
  Capture version: 4.1.0.0
  ...
  16:30:24.2771|INFO|AmongUsCapture.GameMemReader|Connected to Among Us process (13288)
  16:30:24.3032|INFO|AmongUsCapture.GameMemReader|Client verification: "PASS"
  16:30:24.6212|INFO|AmongUsCapture.GameMemReader|GameAssembly sha256: "80553268CE01D4657E47FCAACEBD6A95ADC4BC25C47EB9A64F7DFFD46D387D36"
  16:30:24.6226|INFO|AmongUsCapture.GameMemReader|Loaded offsets: "v2021.5.25.2s"
  16:30:24.6226|INFO|AUCapture_WPF.MainWindow|State change: {"NewState":"MENU"}
  16:30:41.9737|INFO|AUCapture_WPF.MainWindow|State change: {"NewState":"LOBBY"}
  16:30:42.2484|DEBUG|AmongUsCapture.ClientSocket|Room code "ZJDRMF" sent to server
  16:30:42.2484|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Red"}
  16:30:58.2892|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Blue"}
  16:31:00.3882|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Orange"}
  16:31:01.9555|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Yellow"}
  16:31:03.7772|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Green"}
  16:31:06.1458|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Purple"}
  16:31:09.2334|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Cyan"}
  16:31:27.6256|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"White"}
  16:31:29.2144|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"-1"}    👈👈👈👈👈
  16:31:29.2723|INFO|AmongUsCapture.ClientSocket|Connection lost
  ```
* AUCapture `4.1.1` + Among Us `v2021.6.15s`:
  ```
  Capture version: 4.1.1.0
  ...
  15:21:40.9981|INFO|AmongUsCapture.GameMemReader|Connected to Among Us process (5028)
  15:21:41.0769|INFO|AmongUsCapture.GameMemReader|Client verification: "PASS"
  15:21:41.3223|INFO|AmongUsCapture.GameMemReader|GameAssembly sha256: "3D9A88836DEBE9F46928442E387804DB088A573B86E0EB7EC024EC98F6F846AF"
  15:21:41.3223|INFO|AmongUsCapture.GameMemReader|Loaded offsets: "v2021.6.15s"
  ...
  15:59:45.2964|INFO|AUCapture_WPF.MainWindow|State change: {"NewState":"ENDED"}
  15:59:48.5589|INFO|AUCapture_WPF.MainWindow|State change: {"NewState":"LOBBY"}
  15:59:48.6752|DEBUG|AmongUsCapture.ClientSocket|Room code "LMEYHF" sent to server
  15:59:48.6922|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":true, "Disconnected":false, "Color":"Yellow"}
  15:59:48.6986|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Black"}
  15:59:48.6986|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Green"}
  15:59:48.7132|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Lime"}
  15:59:48.7132|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Blue"}
  15:59:48.7270|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Tan"}
  15:59:48.7270|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":true, "Disconnected":false, "Color":"Brown"}
  15:59:48.7432|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":true, "Disconnected":false, "Color":"White"}
  15:59:48.7432|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":true, "Disconnected":false, "Color":"Gray"}
  15:59:49.0023|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Black"}
  15:59:49.3073|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Green"}
  15:59:49.8835|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Lime"}
  15:59:49.9967|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Yellow"}
  15:59:50.0372|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Brown"}
  15:59:56.0911|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Blue"}
  15:59:56.1628|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Gray"}
  15:59:57.2092|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Tan"}
  16:00:28.3271|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Gray"}
  16:00:44.8900|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Gray"}
  16:01:50.8254|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"-1"}    👈👈👈👈👈
  16:01:50.8497|INFO|AmongUsCapture.ClientSocket|Connection lost
  ```
* AUCapture `4.1.2` + Among Us `v2021.6.30s`:
  ```
  Capture version: 4.1.2.0
  ...
  17:26:35.1971|INFO|AmongUsCapture.GameMemReader|Connected to Among Us process (13096)
  17:26:35.2611|INFO|AmongUsCapture.GameMemReader|Client verification: "PASS"
  17:26:35.5523|INFO|AmongUsCapture.GameMemReader|GameAssembly sha256: "10567748DA8DCF1C07FF29C42C3710BC8203930932C0C58564D6748936340070"
  17:26:35.5523|INFO|AmongUsCapture.GameMemReader|Loaded offsets: "v2021.6.30s"
  ...
  17:46:30.8380|INFO|AUCapture_WPF.MainWindow|State change: {"NewState":"ENDED"}
  17:46:34.8524|INFO|AUCapture_WPF.MainWindow|State change: {"NewState":"LOBBY"}
  17:46:34.9710|DEBUG|AmongUsCapture.ClientSocket|Room code "MQVUGF" sent to server
  17:46:34.9868|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":true, "Disconnected":false, "Color":"Yellow"}
  17:46:35.0230|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":true, "Disconnected":false, "Color":"Black"}
  17:46:35.0230|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":true, "Disconnected":false, "Color":"White"}
  17:46:35.0377|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Lime"}
  17:46:35.0377|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Pink"}
  17:46:35.0377|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Blue"}
  17:46:35.0546|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Green"}
  17:46:35.0546|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Left", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Brown"}
  17:46:35.5637|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Black"}
  17:46:35.8904|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"Lime"}
  17:46:35.9289|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"(omit)", "IsDead":false, "Disconnected":false, "Color":"-1"}    👈👈👈👈👈
  ```
* Windows Event Log
  ```
  Application: AmongUsCapture.exe
  CoreCLR Version: 5.0.621.22011
  .NET Version: 5.0.6
  Description: The process was terminated due to an unhandled exception.
  Exception Info: System.Windows.Markup.XamlParseException: Arg_KeyNotFoundWithKey, -1 
   ---> System.Collections.Generic.KeyNotFoundException: Arg_KeyNotFoundWithKey, -1
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at AUCapture_WPF.Converters.PlayerColorToBrush.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
     at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
     at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
     at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
     at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
     at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
     at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
     at System.Windows.StyleHelper.ApplyTemplatedParentValue(DependencyObject container, FrameworkObject child, Int32 childIndex, FrugalStructList`1& childRecordFromChildIndex, DependencyProperty dp, FrameworkElementFactory templateRoot)
     at System.Windows.StyleHelper.InvalidatePropertiesOnTemplateNode(DependencyObject container, FrameworkObject child, Int32 childIndex, FrugalStructList`1& childRecordFromChildIndex, Boolean isDetach, FrameworkElementFactory templateRoot)
     at System.Windows.FrameworkTemplate.InvalidatePropertiesOnTemplate(DependencyObject container, Object currentObject)
     at System.Windows.FrameworkTemplate.<>c__DisplayClass45_0.<LoadOptimizedTemplateContent>b__2(Object sender, XamlObjectEventArgs args)
     at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
     at System.Xaml.XamlObjectWriter.WriteEndObject()
     at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
     Exception_EndOfInnerExceptionStack
     at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
     at System.Windows.Markup.XamlReader.RewrapException(Exception e, Uri baseUri)
     at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
     at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
     at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
     at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
     at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
     at System.Windows.FrameworkElement.ApplyTemplate()
     at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
     at System.Windows.UIElement.Measure(Size availableSize)
     at System.Windows.Controls.Primitives.UniformGrid.MeasureOverride(Size constraint)
     at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
     at System.Windows.UIElement.Measure(Size availableSize)
     at System.Windows.ContextLayoutManager.UpdateLayout()
     at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
     at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
     at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
     at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location ---
     at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
     at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
     at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
     at System.Windows.Threading.Dispatcher.Run()
     at System.Windows.Application.RunDispatcher(Object ignore)
     at System.Windows.Application.RunInternal(Window window)
     at System.Windows.Application.Run()
     at AUCapture_WPF.App.Main()
  ```

## To Reproduce

1. Start AUCapture and Among Us, then create Lobby
2. Ask other players to join in

## Expected behavior

AUCapture keeps working.

## Additional context

I suspect that this is a timing issue with the communication with the Among Us server and reading RAM by AUCapture.

When receiving information about other players from the Among Us server, there may be a moment during the initialization process when the color ID is temporarily set to `-1`, I think.

**Comment by CarbonNeuron** [comment]
This just needs to be caught in the brush converter. But also this is a problem because color is an enum, -1 is not going to be part of that.

**Comment by kurokobo** [comment]
It seems that when a user joins a lobby, a player instance is initially created in memory with an empty name and "-1" color, and then the name and color are updated.
Also, during this initialization process, there seems to be a moment when only the name is updated, but the color remains "-1".

I shortened the loop period of AUCapture **from 250ms to 10ms** and added a Logger to the end of the constructor of the PlayerInfo class;

```csharp
Logger.Info("RawPlayerInfo: {}, {}, {}, {}, {}", PlayerName, ColorId, RoleType, RoleTeamType, Disconnected, Disconnected, IsImpostor);
```

and got the following output.

* Usual case
  ```
  05:55:44.6232|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:44.6232|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:44.6449|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:44.6449|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "", -1, 0, 0, false    👈👈👈👈👈　Player instance created
  05:55:44.6558|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:44.6558|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "", -1, 0, 0, false
  ...
  05:55:44.9777|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:44.9777|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "", -1, 0, 0, false
  05:55:44.9888|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:44.9888|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Twokite", Red, 0, 0, false    👈👈👈👈👈　Update name and color at the same time
  05:55:44.9888|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"Twokite", "IsDead":false, "Disconnected":false, "Color":"Red"}    👈👈👈👈👈　"Joined" event invoked with correct data
  ```
* Invalid case
  ```
  05:55:54.3585|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.3585|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.3803|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.3912|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.3912|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "", -1, 0, 0, false    👈👈👈👈👈　Player instance created
  05:55:54.3912|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.3912|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "", -1, 0, 0, false
  ...
  05:55:54.6803|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.6803|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "", -1, 0, 0, false
  05:55:54.6913|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.6913|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "", -1, 0, 0, false
  05:55:54.7030|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Rounddust", Black, 0, 0, false
  05:55:54.7030|INFO|AmongUsCapture.PlayerInfo|RawPlayerInfo: "Twokite", -1, 0, 0, false    👈👈👈👈👈　Only name is updated and its color is still -1
  05:55:54.7030|DEBUG|AUCapture_WPF.MainWindow|{"Action":"Joined", "Name":"Twokite", "IsDead":false, "Disconnected":false, "Color":"-1"}    👈👈👈👈👈　"Joined" event invoked with invalid color id
  ```

**Comment by kurokobo** [comment]
I think adding new enum `PlayerColor.Unknown = -1` and changing this line:
```csharp
if(pi.GetPlayerName() is null || pi.GetPlayerName() == "") continue;
```
https://github.com/automuteus/amonguscapture/blob/master/AmongUsCapture/Memory/GameMemReader.cs#L108

as following will solve this issue.
```csharp
if(pi.GetPlayerName() is null || pi.GetPlayerName() == "" || pi.GetPlayerColor() == PlayerColor.Unknown) continue;
```
